### ISSUE TITLE
Run on ios using C++

### ISSUE THREAD

**Issue by foxfortmobile** [kunzmi/ImageStackAlignator#1]
Hi,

Is it possible to run this code on device in C++ on ios RAW DNG files? Does it have any specific hardware limitations that prevents it from being run on other platform? I don't have GPU since i use an old Macbbook so i could not try the demo.

**Comment by kunzmi** [comment]
Well, the main (and computationally heavy) parts are implemented in CUDA, with some glue code in C# plus a simple GUI. So that gives you the restriction of having a Nvidia GPU... If you remove the WPF GUI and replace it with some other way of interaction, you could run the glue code with mono on your mac. But you'd still need a GPU, though.
So the short answer is: no

**Comment by foxfortmobile** [comment]
Ok, thanks for the quick reply
